server:
  port: 8080
  servlet:
    context-path: /pickup_SpringBoot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pick_up?useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mybatis/*.xml